### ISSUE TITLE
I can't get this to work on python 3.4 windows.

### ISSUE THREAD

**Issue by pteek** [feross/SpoofMAC#22]
I 2to3ed the whole folder because I saw some incompatible functions.
I had to rename the script spoof-mac to spoof-mac.py to get a prompt. This was in C:\python34\Scripts

spoof-mac list gives this:

Traceback (most recent call last):
  File "C:\Python34\Scripts\spoof-mac.py", line 5, in <module>
    pkg_resources.run_script('SpoofMAC==1.2.1', 'spoof-mac')
  File "C:\Python34\lib\site-packages\setuptools-3.3-py3.4.egg\pkg_resources.py"
, line 528, in run_script
    self.by_key[dist.key] = dist
  File "C:\Python34\lib\site-packages\setuptools-3.3-py3.4.egg\pkg_resources.py"
, line 1401, in run_script
    def _has(self, path):
  File "C:\Python34\lib\site-packages\spoofmac-1.2.1-py3.4.egg\EGG-INFO\scripts\
spoof-mac", line 123, in <module>
AttributeError: 'module' object has no attribute 'geteuid'

This is of course a *nix call.

What now?
